// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://betxwzazlsgdeegxhquk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldHh3emF6bHNnZGVlZ3hocXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NjM4NDAsImV4cCI6MjA3NzMzOTg0MH0.Pj4cn1RK15zHZJpGthEao7XURnnt-nPoQ4hh2LjjpJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});